### ISSUE TITLE
Make build environment variables persistent in VSTS 

### ISSUE THREAD

**Issue by Stijnc** [RamblingCookieMonster/BuildHelpers#14]
When using multiple tasks in Visual Studio Team Foundation you need to persist the variables using specific VSTS tasks.

$env:variablename only lives in the current task.
using [VSTS tasks](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md) makes the variable persistent cross tasks.

I propose to add VSTS specific logic to the Set-BuildEnvironment function to make those persistent?
What do you think?

**Comment by RamblingCookieMonster** [comment]
Makes sense to me if you're up for it!

I'm thinking further down the road it might be worth adding a `Get-BuildEnvironment` function that spits out a property bag.  This could be used by `Set-BuildEnvironment`, on top of allowing the user to work with the data as needed (e.g. serialize to disk or some other more persistent method)

Cheers!

**Comment by Stijnc** [comment]
Hi Warren,

Finally have some time again and this is still on my todo list. 
I will start with making sure the environment variables are persistent cross taks in the VSTS and submit a pull request in the near future.
Let's discuss the property bag approach for a next pull request?

**Comment by lipkau** [comment]
If someone  has time (or a use-case) to test this, I implemented this in the following branch:

https://github.com/lipkau/BuildHelpers/tree/feature/persistentVariableOnVSTS
