### ISSUE TITLE
Set-ModuleFunctions: New line added to the end of ModuleManifest

### ISSUE THREAD

**Issue by chelnak** [RamblingCookieMonster/BuildHelpers#27]
Each time we run a build and process the module manifest with Set-ModuleFunctions a new line will be added to the end of the file, resulting in unnecessary commits.

## Example commit:
https://github.com/jakkulabs/PowervRA/commit/c99f58d99723ebbe8d15b36a2e1d3a45998b8fe7

## Build:
https://ci.appveyor.com/project/JakkuLabs/powervra/build/2.0.0.87

This happens locally and within appveyor (Both WMF 5)

I think this might be being caused by the Update-Metadata function? More research needed on my part, but if you have any more information that would be cool.

**Comment by RamblingCookieMonster** [comment]
Hi!  Changed that function up to write files without appending a new line.  Seemed to work with a quick test.  Hit me up if it's still broken for you, and thanks for the heads up!

**Comment by chelnak** [comment]
Just tested and it's looking good to me! Thanks for such a quick turn around.
