### ISSUE TITLE
Set-ModuleFunctions change encoding to UTF8 without BOM

### ISSUE THREAD

**Issue by RobDesideri** [RamblingCookieMonster/BuildHelpers#36]
`Set-ModuleFunctions` in BuildHelpers change the manifest file encoding to UTF8 **without** BOM.

This is a problem, following the [UseBOMForUnicodeEncodedFile](https://github.com/PowerShell/PSScriptAnalyzer/blob/development/RuleDocumentation/UseBOMForUnicodeEncodedFile.md) PSScriptAnalyzer rule.

I verified that the cause is the version `0.8` of [PoshCode Configuration](https://github.com/PoshCode/Configuration) Module.

I also verified that in the latest version of the `Configuration` module (version `1.0.2` ) this issue is solved (see [commit](https://github.com/PoshCode/Configuration/commit/845f80dcd1e9748cf02f3fc9913933833505b408)).

Updating `Configuration` to latest version, this issue should be removed.

**Comment by RamblingCookieMonster** [comment]
Hiyo!

Thanks for the heads up, definitely need to update the Configuration module embedded here!

It might be worth opening an issue on PSScriptAnalyzer - [this RFC](https://github.com/PowerShell/PowerShell-RFC/blob/master/2-Draft-Accepted/RFC0020-DefaultFileEncoding.md) was accepted and will change the default encoding will allow UTF8 without BOM.

For now, going to leave this with no BOM to keep it future proof - you could ignore that rule in scriptanalyzer, or we could add an encoding param to the `metadata` commands - I'm a bit wary of that though - not sure how long it would take to get upstream, and don't want to patch the outdate version on my side.  Sort of an odd situation, but if it's causing a problem, I'd be open to either... I suppose the metadata commands likely won't change much, so patching in the embedded module would work for me, if you're interested

Cheers!

**Comment by RobDesideri** [comment]
Hi @RamblingCookieMonster 
Ok, sure! Can you assign me this issue? So my automated workflow kick off... ;)

**Comment by RamblingCookieMonster** [comment]
Hiyo!  Closing this out

Another option would be to add a `-Encoding` parameter on Set-ModuleFunctions, with corresponding handling and parameter passing to the function in the Configuration module - if anyone wants to take a stab at that, feel free to open this back up

Cheers!
