### ISSUE TITLE
Easy Integration with PSSlack for Build Tools

### ISSUE THREAD

**Issue by russellds** [RamblingCookieMonster/BuildHelpers#38]
I started writing a helper module for easy integration of PSSlack initially with Invoke-Build and plans to add psake as well. The first version was to be able to be able to add just one line of code to Invoke-Build's Enter-Build, Enter-BuildTask, Exit-BuildTask, and Exit-Build to get notifications of the build process in Slack. Additionally, I had plans to add the same type of functions that you have in the BuildHelpers module. 

After looking at your BuildHelpers module I am thinking that it might make more sense to just submit a pull request to add that functionality to BuildHelpers instead of creating a different module. Would you be open to that?

Here is a link to the module that I started if you want to take a look: [buildHelper](https://github.com/russellds/buildHelper). It is a bit rough because it just wrapped up the prototype phase and now I am starting to clean it up and add all of the missing stuff.

**Comment by russellds** [comment]
One minor update, I renamed the module that I am working on to [SlackBuildHelper](https://github.com/russellds/SlackBuildHelper) to reduce any confusion.

**Comment by russellds** [comment]
After using the BuildHelpers module I realize that integrating PSSlack into it isn't the right idea. I am going to close this issue.

**Comment by RamblingCookieMonster** [comment]
Hiyo! Sorry about the delay, been on vacation! I do like the idea of commands to track timing - other build tools do offer it, but a generalized option that could work across these might be nice!

**Comment by russellds** [comment]
If you are interested, I am more than willing to see how they could be integrated. At first, I was thinking that it might be difficult to pool off for something like AppVeyor, but with the AppVeyor encrypted variables it wouldn't be too hard. Your call as to whether it should be something stand alone or you would like to integrate it into BuildHelpers.
