### ISSUE TITLE
Add VSTS as a Build System

### ISSUE THREAD

**Issue by Stijnc** [RamblingCookieMonster/BuildHelpers#4]
I use Visual Studio Team Services quite a lot and would like to see VSTS included as a build system.
If you like I can submit a pull request.

The only remaining questions I have are:
1. you make use of package management, currently VSTS hosted agents only have PowerShell v4 running and we're not able to install additional software
2. Your tests include PowerShell v5 functionality like New-Guid

Would you like me to make it v4 compatible?
The only file that does get modified is Get-BuildVariables, but no tests target the function if I'm correct.

I've forked your repository and have a working version for VSTS, but it only takes Git repositories into account, not TFS and the module import is a but quick and dirty.
[forked BuildHelpers](https://github.com/Stijnc/BuildHelpers)

![Image of VSTS build Environment](https://raw.githubusercontent.com/Stijnc/BuildHelpers/master/Media/VSTS%20(former%20VSO).png)

Thanks,
Stijn

**Comment by RamblingCookieMonster** [comment]
Hi Stijn!

Awesome, thanks for the note, was hoping to get more build systems in here, personally haven't had the chance to work with VSTS yet.

A few quick questions:

* Would it make sense to make the module itself PowerShell 4 compatible? I do think some of @cdhunt's version code uses PowerShell 5 specific code.  We might be able to borrow or rely on @Jaykul's Configuration module [metadata code/functions](https://github.com/PoshCode/Configuration/blob/master/Metadata.psm1) to provide this, had already been tinkering with this for other uses

* Is there any requirement to have the build process for this module - not the module itself - PowerShell 4 compatible?  I can see a few scenarios for this, but see it as a bit lower priority (most of the build process is designed to simplify collaboration and publication, vs. be used outside of AppVeyor).

If you want to start with a PR for the VSTS env variables, that would be awesome : D

Cheers!

**Comment by cdhunt** [comment]
The `Step-ModuleVersion` function does use the `*-ModuleManifest` cmdlets in v5.

**Comment by Stijnc** [comment]
I don't really see a benefit in making the build process for the module itself v4 compatible, I just had to do some plumbing to kick of a build in VSTS.

Let me submit a pull request for the VSTS environment variables and we'll start from there.

**Comment by RamblingCookieMonster** [comment]
Deployed! Thanks for the PR : )
