### ISSUE TITLE
Update-MetaData: How to increment to the next major version automatically

### ISSUE THREAD

**Issue by Midacts** [RamblingCookieMonster/BuildHelpers#41]
This is more of a RFI, but how do you guys increment your module version in your buiilds to the next major/minor release version?
`Update-Metadata -Path $ENV:BHPSModuleManifest`

Example:
0.1.11 to 0.2.0
or
0.1.11 to 1.0.0

**Comment by michaeltlombardi** [comment]
I tend to do major/minor by hand as a commit.

**Comment by Midacts** [comment]
Makes sense.
I just wanted to make sure I wasn't missing out.
