### ISSUE TITLE
BHCommitMessage has extra space when used in AppVeyor

### ISSUE THREAD

**Issue by PlagueHO** [RamblingCookieMonster/BuildHelpers#55]
In AppVeyor the BHCommitMessage is generated by combining the variables:
`"$env:APPVEYOR_REPO_COMMIT_MESSAGE $env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED"`

But if the `$env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED` is empty (which it often is) then the commit message contains an extra space.

This isn't a major issue, but I was attempting to use a regex match (`$env:BHCommitMessage -match ' Deploy!$'`) to detect a deploy commit, but couldn't figure out why this wouldn't work.

Might be worth trimming this value: https://github.com/RamblingCookieMonster/BuildHelpers/blob/master/BuildHelpers/Public/Get-BuildVariables.ps1#L153

```powershell
"$env:APPVEYOR_REPO_COMMIT_MESSAGE $env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED".TrimEnd()
```

Alternately you could check to see if `$env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED` is empty before appending it and a space. I've worked around by TrimEnd() the value before using it.

Happy to submit a PR with a solution if you want?

**Comment by RamblingCookieMonster** [comment]
Makes sense to me! Trimend example makes sense - if you have time, PR would be awesome

Thanks!
