### ISSUE TITLE
Add TeamCity as build system

### ISSUE THREAD

**Issue by Plork** [RamblingCookieMonster/BuildHelpers#6]
We use Teamcity as build system and I thought I take a look at how to add it to BuildHelpers.

One of the issues I found is that Teamcity is very scarce with it's $ENV variables. You can pass any Teamcity variable to the build if you want, but that requires specific build configurations. I wasn't sure if you want to go that way? personally I like it if a module just works without tweaking settings and configuring things in a certain way.

One thing I found it that Teamcity dumps all the variables in an XML file that you can load and parse.

At the moment I made a private function that loads the XML and adds the variables I need to a $ENV variable.

The other thing I am struggling with is that Teamcity doesn't do commit messages. Teamcity can bundle several commits into 1 build or only build every 15 minutes or whatever you specify. So this can become quite tricky to get the commit message from Teamcity.

Any suggestion on the commit message part?

**Comment by RamblingCookieMonster** [comment]
Hi!

Good question on the commit message side.  A few options:

* If it exists, read data from XML that tells us how many new commits this build touches.  Use git to extract commit message from all, concatenate.
* Assume one-commit granularity.  Use git to grab the last commit.  Given the functionality you describe, this route might be a poor choice.
* Give up : P  Or, if the first bullet isn't an option, and the second bullet isn't reflective of the actual commit messages (i.e. it would only include 1 even if more were included), assume no data is better than bad data, return $null for this.

For the XML side, feel free to add handling to Get-BuildVariables that reads from that XML if it's present.

Cheers!

**Comment by Plork** [comment]
Seems Teamcity does not pass a lot of variables by design to the build agent. (not even in the property file). It does not even pass along the server url in a variable otherwise I could use the API to get that information.

In other words You need to configure you build to pass along variables to the agent for use of BuildHelpers.

Don't know if that matches with the philosophy behind BuildHelpers?
