### ISSUE TITLE
Add function: Get files changed in git commit

### ISSUE THREAD

**Issue by RamblingCookieMonster** [RamblingCookieMonster/BuildHelpers#7]
Get-GitChangedFile, or something along those lines

Parameters:

* Commit - defaults to most recent (e.g. `git rev-parse HEAD`)
* Filter - some sort of filter functionality to include/exclude files returned
* Others?

Ultimately, logic might boil down to something like this:

```powershell
git diff-tree --no-commit-id --name-only -r $Commit
```

Example use case: if your repository involves multiple individual-file deployments, this is one way to identify whether to deploy them (ideally you validate against deployed item, this is just an option).

**Comment by michaeltlombardi** [comment]
A use case for us: I only want to bother publishing my docs if (and only if!) something in my docs or the docs config has changed. 

Similarly, if the changes being committed don't include changes to the code itself, I don't want to trigger an attempt to test/build/publish the module.

Literally just came looking for this functionality. :)

**Comment by michaeltlombardi** [comment]
Simple workaround I just put in place:

```powershell
$FilesChanged = git diff-tree --no-commit-id --name-only -r (git log --format=%h -n 1)
$DocumentsUpdated = $FilesChanged | Where-Object -FilterScript {$_ -match "^docs" -or $_ -eq "mkdocs.yml"}
$SourceFilesChanged = $FilesChanged | Where-Object -FilterScript {$_ -match "^(Source|Functions|Dependencies)"}

If( $Env:BHBranchName -eq 'master'){
    $TaskList = @()
    If ($SourceFilesChanged.Count -gt 0) {
        Write-Output "$($SourceFilesUpdated.Count) Source Files Updated on Master; Triggering Deployment"
        $TaskList += "Deploy"
    } 
    If ($DocumentsChanged.Count -gt 0)   {
        Write-Output "$($DocumentsUpdated.Count) Documents Updated on Master; Triggering Publishing"
        $TaskList += "Publish"
    }
}

If ($TaskList.Count -gt 0) {
    Write-Output "Executing Tasks: $TaskList`r`n"
    Invoke-Psake -buildFile $ProjectRoot\psake.ps1 -properties $PSBoundParameters -noLogo -taskList $TaskList
} Else {
    Write-Output "Executing Unit Tests Only`r`n"
    Invoke-Psake -buildFile $ProjectRoot\psake.ps1 -properties $PSBoundParameters -nologo
}
```

This example just uses some logic to see if we're on the master branch and, if so, whether source files or documents changed. If they did, trigger the appropriate build tasks.

**Comment by RamblingCookieMonster** [comment]
Alrighty!  Added an initial stab at this function and a few superficial tests - hit me up if there's anything missing (or when you find an the inevitable bugs)

Cheers!
