### ISSUE TITLE
Cmdlets with plural form

### ISSUE THREAD

**Issue by lipkau** [RamblingCookieMonster/BuildHelpers#72]
The following public functions are in plural form; whereas Powershell recommends nouns to be in singular:

* `Get-BuildVariables`
* `Get-ModuleAliases`
* `Get-ModuleFunctions`
* `Set-ModuleAliases`
* `Set-ModuleFormats`
* `Set-ModuleFunctions`

**Comment by RamblingCookieMonster** [comment]
Yeah, it's against standards... but... each of those explicitly works with sets of things (i.e. never a single thing), or are named after what they work with (e.g. Set-ModuleAliases is working with AliasesToExport, not AliasToExport).

Even ignoring that, I think at this point, given that they're already in place, I'd just as rather leave them be.

If folks feel really adamant about this, feel free to debate in here!  If there are good functional reasons to change this, would be happy to do so (of course, we would need to leave existing functions as aliases, so... seems like it would be overcomplicating things)

**Comment by LaurentDardenne** [comment]
Hi,
may be using  [Obsolete()] attribut ?

**Comment by pauby** [comment]
As the module is to help people have a set of standard functions they can rely on, I think they should follow a standard themselves (ie. recommended best practice)

As you say you can always use aliases to keep everything working as it was for people.

**Comment by lipkau** [comment]
@LaurentDardenne 
using `[Obsolete()]` would break compatibility with PSv3 (which is given in the manifest `PowerShellVersion = '3.0'`)

**Comment by lipkau** [comment]
I agree with @pauby

**Comment by RamblingCookieMonster** [comment]
Alrighty! If someone wants to take a stab at a PR I’m open to it, as long as we add the aliases in there.

**Comment by pauby** [comment]
I'll take a look.

**Comment by pauby** [comment]
> oh...l I am halfway done, @pauby :-P

Cool. This was originally raised three months ago so I assumed it wasn't being worked on.

I'll leave it alone 👍
