### ISSUE TITLE
BHBuildSystem is Unknow in VSTS

### ISSUE THREAD

**Issue by lipkau** [RamblingCookieMonster/BuildHelpers#76]
`$env:BHBuildSystem` is `Unknown` in VSTS when in called in the Release pipeline

**Comment by RamblingCookieMonster** [comment]
Eek, guessing they updated environment variables they provide?  There's likely a better candidate than [the current one](https://github.com/RamblingCookieMonster/BuildHelpers/blob/master/BuildHelpers/Public/Get-BuildVariables.ps1#L97) - happy to take a PR on this (assuming it applies across VSTS?  Is there a split now or did all VSTS things become Azure DevOps?  Haven't kept track)

**Comment by PlagueHO** [comment]
Yah, I noticed this one as well and was going to get round to submitting a PR. Build pipelines are fine (and still show as VSTS build system), but release pipelines don't.
