### ISSUE TITLE
Add function: Compare content to PSGallery

### ISSUE THREAD

**Issue by RamblingCookieMonster** [RamblingCookieMonster/BuildHelpers#9]
Potential names: `Compare-PSGalleryModuleContent` and `Compare-PSGalleryScriptContent`

Input: PSRepository, ModulePath, ModuleName (Derived from ModulePath potentially?) Version (default to latest, if we even offer this)

Pull down latest version of a module (or script) from PSGallery, compare contents with a specified local module.

Example use case:  In scenarios where multiple scripts or modules are deployed from a single repository, these functions could be used to validate that files have been changed between the current data, and the PSGallery data.

**Comment by Plork** [comment]
This get's tough I think when a module has binaries :S

I have been doing this now by comparing the version number. but the drawback is you have to manually bump the version if you want to deploy something.

**Comment by RamblingCookieMonster** [comment]
Yeah, like you said, this is what versioning is for, closing this out!
