### ISSUE TITLE
Get-BuildEnvironment should expose commit hash

### ISSUE THREAD

**Issue by terrabitz** [RamblingCookieMonster/BuildHelpers#92]
Currently, `Get-BuildEnvironment` exposes the current commit message as an environment variable, but not the commit hash. I feel like there may be value for certain pipelines in exposing the commit hash or shortened hash as another environment variable. For example, I am working on a pipeline that automatically takes any build that passes its tests, puts the shortened commit hash as the prerelease string, and then pushes it to my ProGet instance as a prerelease version.

Theoretically, this should be doable via git (`git log -n 1 --format='%H'`) or exposed variables in most build systems (e.g. `$env:APPVEYOR_REPO_COMMIT`).

**Comment by FISHMANPET** [comment]
the azure pipelines variable is BUILD_SOURCEVERSION for this

**Comment by FISHMANPET** [comment]
Appveyor: APPVEYOR_REPO_COMMIT
Gitlab ci: CI_COMMIT_SHA
Jenkins: GIT_COMMIT
Teamcity: BUILD_VCS_NUMBER
Azure Pipelines: BUILD_SOURCEVERSION
Bamboo: BAMBOO_PLANREPOSITORY_REVISION
GoCD: GO_REVISION
Travis: TRAVIS_COMMIT
Github Actions: GITHUB_SHA

Out of curiosity, I see a lot of the BH variables are set by reading values from Git vs finding environment variables that the build system creates, is there any particular reason for that, or is it just what happened to be the easiest for you to code against build systems you weren't familiar with?
