### ISSUE TITLE
GitHub Action support

### ISSUE THREAD

**Issue by devblackops** [RamblingCookieMonster/BuildHelpers#96]
This is more of an FYI.

I'm experimenting with various PowerShell use cases in GitHub Actions and some of them use `BuildHelpers` to determine some folder paths. I receive the following error when running `Set-BuildEnvironment -Force` when run within an Action.

```
Cannot index into a null array.
At /github/home/.local/share/powershell/Modules/BuildHelpers/2.0.0/Public/Get-BuildVariables.ps1:78 char:9
+         $GitPath = (Get-Command $GitPath -ErrorAction SilentlyContinu ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : NullArray
```

I'm going to dig into this more and _hopefully_ submit a fix.

**Comment by RamblingCookieMonster** [comment]
Interesting - is git not available?  I think that just runs ‘get-command git’, picks first in case multiple results come back (that’s where error is coming up - indexing into nothing)

**Comment by devblackops** [comment]
Ah ya, right...git is probably not on the image I'm using (`mcr.microsoft.com/powershell:6.1.0-ubuntu-18.04`). I'll add that and try again. Thanks!

**Comment by devblackops** [comment]
Failing gracefully would be nice. And having official support for Action env vars would be sweet!
